services:
  web:
    build: .
    volumes:
      - .:/app # Mount current code for live reload
      - db_data:/app/data # Persist (save) SQLite file
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on: []
    restart: unless-stopped

volumes:
  db_data:
