global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "web"
    metrics_path: /metrics
    static_configs:
      - targets: ["web:8000"]   # container name + port

  # Celery worker metrics exporter (from home/metrics.py)
  - job_name: "worker"
    metrics_path: /metrics
    static_configs:
      - targets: ["worker:9091"]  # CELERY_METRICS_PORT

  # Scrape Prometheus itself (optional)
  - job_name: "prometheus"
    metrics_path: /metrics
    static_configs:
      - targets: ["prometheus:9090"]