# Generated by Django 5.2.4 on 2025-07-17 17:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name="TimingTodo",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "schedule_date",
                    models.DateField(help_text="Date on which the todo is scheduled"),
                ),
                (
                    "start_time",
                    models.TimeField(
                        blank=True, help_text="When the task starts", null=True
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        blank=True, help_text="When the task ends", null=True
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes about the timing",
                        null=True,
                    ),
                ),
                (
                    "todo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.todo"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
