# Generated by Django 5.2.4 on 2025-07-17 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_todo_created_at_alter_todo_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timingtodo",
            name="todo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timingtodos",
                to="home.todo",
            ),
        ),
    ]
