# Generated by Django 5.2.4 on 2025-07-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_remove_timingtodo_user_todo_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="username",
            field=models.TextField(null=True),
        ),
    ]
