# Generated by Django 5.2.4 on 2025-07-18 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_todo_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="username",
        ),
    ]
