# Generated by Django 5.2.4 on 2025-07-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_timingtodo_due_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timingtodo",
            name="due_date",
        ),
        migrations.AddField(
            model_name="todo",
            name="session_key",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
